# Generated by Django 3.2.8 on 2021-12-01 08:04

from django.db import migrations, models
import django.db.models.deletion
import homepage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, editable=False, help_text='자동 지정(입력 X)', max_length=20)),
                ('ext', models.CharField(blank=True, editable=False, help_text='자동 지정(입력 X)', max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False)),
                ('video_ok', models.BooleanField(default=False, help_text='동영상 파일을 업로드 할 경우 체크해주세요!!', verbose_name='동영상 여부: ')),
                ('src', models.FileField(blank=True, upload_to=homepage.models.product.auto_naming)),
                ('prefix', models.CharField(default='product_source/', max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.product_list')),
            ],
            options={
                'verbose_name_plural': '제품',
            },
        ),
    ]
