# Generated by Django 3.2.8 on 2021-11-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_bigcoating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='general', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/bigcoating/')),
                ('prefix', models.CharField(default='product_source/bigcoating/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '대형코팅',
            },
        ),
        migrations.CreateModel(
            name='product_bindding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='binding', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/binding/')),
                ('prefix', models.CharField(default='product_source/binding/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '제본(현재 사용 x)',
            },
        ),
        migrations.CreateModel(
            name='product_binder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='binder', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/binder/')),
                ('prefix', models.CharField(default='product_source/binder/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '바인더',
            },
        ),
        migrations.CreateModel(
            name='product_catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='catalog', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/catalog/')),
                ('prefix', models.CharField(default='product_source/catalog/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '카탈로그',
            },
        ),
        migrations.CreateModel(
            name='product_creature_of_prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='creature_of_prize', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/creature_of_prize/')),
                ('prefix', models.CharField(default='product_source/creature_of_prize/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '상패',
            },
        ),
        migrations.CreateModel(
            name='product_drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='drawing', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/drawing_binding/')),
                ('prefix', models.CharField(default='product_source/drawing_binding/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '도면(반책) 제본',
            },
        ),
        migrations.CreateModel(
            name='product_envelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='envelope', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/envelope/')),
                ('prefix', models.CharField(default='product_source/envelope/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '봉투',
            },
        ),
        migrations.CreateModel(
            name='product_etc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='etc', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/etc/')),
                ('prefix', models.CharField(default='product_source/etc/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '기타(현재 사용 X)',
            },
        ),
        migrations.CreateModel(
            name='product_exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='exhibit', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/exhibit/')),
                ('prefix', models.CharField(default='product_source/exhibit/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '전시회 백월 포스터',
            },
        ),
        migrations.CreateModel(
            name='product_form_board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='formboard', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/formboard/')),
                ('prefix', models.CharField(default='product_source/formboard/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '폼보드',
            },
        ),
        migrations.CreateModel(
            name='product_general_binding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='general', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/general_binding/')),
                ('prefix', models.CharField(default='product_source/general_binding/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '보고서 책자 및 교본',
            },
        ),
        migrations.CreateModel(
            name='product_hard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='hard', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/hard_binding/')),
                ('prefix', models.CharField(default='product_source/hard_binding/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '하드커버 제본',
            },
        ),
        migrations.CreateModel(
            name='product_index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='index', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/index/')),
                ('prefix', models.CharField(default='product_source/index/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '인덱스(색인)',
            },
        ),
        migrations.CreateModel(
            name='product_invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='invite', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/invite/')),
                ('prefix', models.CharField(default='product_source/invite/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '초대장',
            },
        ),
        migrations.CreateModel(
            name='product_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': '제품 리스트',
            },
        ),
        migrations.CreateModel(
            name='product_memorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='memorial', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/memorial/')),
                ('prefix', models.CharField(default='product_source/memorial/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '기념품',
            },
        ),
        migrations.CreateModel(
            name='product_namecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='namecard', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/namecard/')),
                ('prefix', models.CharField(default='product_source/namecard/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '명함',
            },
        ),
        migrations.CreateModel(
            name='product_nametag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='nametag', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/nametag/')),
                ('prefix', models.CharField(default='product_source/nametag/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '명찰',
            },
        ),
        migrations.CreateModel(
            name='product_paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='formboard', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/paper/')),
                ('prefix', models.CharField(default='product_source/paper/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '논문',
            },
        ),
        migrations.CreateModel(
            name='product_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='photo', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/photo')),
                ('prefix', models.CharField(default='product_source/photo', max_length=50)),
            ],
            options={
                'verbose_name_plural': '상업용 사진',
            },
        ),
        migrations.CreateModel(
            name='product_post_it',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='postit', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/postit/')),
                ('prefix', models.CharField(default='product_source/postit/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '포스트 잇',
            },
        ),
        migrations.CreateModel(
            name='product_poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='poster', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/poster/')),
                ('prefix', models.CharField(default='product_source/poster/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '포스터/학회포스터',
            },
        ),
        migrations.CreateModel(
            name='product_print',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='print', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/print/')),
                ('prefix', models.CharField(default='product_source/print/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '출력',
            },
        ),
        migrations.CreateModel(
            name='product_prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='prize', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/prize/')),
                ('prefix', models.CharField(default='product_source/prize/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '상장 / 단증 / 자격증',
            },
        ),
        migrations.CreateModel(
            name='product_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='report', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/report')),
                ('prefix', models.CharField(default='product_source/report/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '보고서/제안서',
            },
        ),
        migrations.CreateModel(
            name='product_report_box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='report_box', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/report_box/')),
                ('prefix', models.CharField(default='product_source/report_box/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '제안서 박스',
            },
        ),
        migrations.CreateModel(
            name='product_shoppingbag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='shoppingbag', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/shoppingbag/')),
                ('prefix', models.CharField(default='product_source/shoppingbag/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '쇼핑백',
            },
        ),
        migrations.CreateModel(
            name='product_spring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='spring', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/spring_binding/')),
                ('prefix', models.CharField(default='product_source/spring_binding/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '스프링 제본',
            },
        ),
        migrations.CreateModel(
            name='product_sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='sticker', max_length=20)),
                ('ext', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False, help_text='이미지를 파일 추가를 해서 입력 하면 체크', verbose_name='이미지 직접 추가 여부:')),
                ('img', models.ImageField(blank=True, upload_to='product_source/sticker/')),
                ('prefix', models.CharField(default='product_source/sticker/', max_length=50)),
            ],
            options={
                'verbose_name_plural': '스티커',
            },
        ),
    ]
