# Generated by Django 3.2.9 on 2021-12-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='link_ok',
        ),
        migrations.AlterField(
            model_name='product',
            name='prefix',
            field=models.CharField(default='product_source/', editable=False, max_length=50),
        ),
    ]
