# Generated by Django 3.2.8 on 2021-11-29 06:03

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='album', editable=False, help_text='자동 지정(입력 X)', max_length=20)),
                ('ext', models.CharField(blank=True, editable=False, help_text='자동 지정(입력 X)', max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False)),
                ('video_ok', models.BooleanField(default=False, help_text='동영상 파일을 업로드 할 경우 체크해주세요!!', verbose_name='동영상 여부: ')),
                ('src', models.FileField(blank=True, upload_to=homepage.models.product_album.auto_naming)),
                ('prefix', models.CharField(default='product_source/album', max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '앨범',
            },
        ),
        migrations.CreateModel(
            name='product_bici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='bici', editable=False, help_text='자동 지정(입력 X)', max_length=20)),
                ('ext', models.CharField(blank=True, editable=False, help_text='자동 지정(입력 X)', max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False)),
                ('video_ok', models.BooleanField(default=False, help_text='동영상 파일을 업로드 할 경우 체크해주세요!!', verbose_name='동영상 여부: ')),
                ('src', models.FileField(blank=True, upload_to=homepage.models.product_bici.auto_naming)),
                ('prefix', models.CharField(default='product_source/bici', max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'BI & CI',
            },
        ),
        migrations.CreateModel(
            name='product_hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='hospital', editable=False, help_text='자동 지정(입력 X)', max_length=20)),
                ('ext', models.CharField(blank=True, editable=False, help_text='자동 지정(입력 X)', max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False)),
                ('video_ok', models.BooleanField(default=False, help_text='동영상 파일을 업로드 할 경우 체크해주세요!!', verbose_name='동영상 여부: ')),
                ('src', models.FileField(blank=True, upload_to=homepage.models.product_hospital.auto_naming)),
                ('prefix', models.CharField(default='product_source/hospital', max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '각종 병원 양식',
            },
        ),
        migrations.CreateModel(
            name='product_printout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='printout', editable=False, help_text='자동 지정(입력 X)', max_length=20)),
                ('ext', models.CharField(blank=True, editable=False, help_text='자동 지정(입력 X)', max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False)),
                ('video_ok', models.BooleanField(default=False, help_text='동영상 파일을 업로드 할 경우 체크해주세요!!', verbose_name='동영상 여부: ')),
                ('src', models.FileField(blank=True, upload_to=homepage.models.product_printout.auto_naming)),
                ('prefix', models.CharField(default='product_source/printout', max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '각종 인쇄',
            },
        ),
        migrations.AddField(
            model_name='product_list',
            name='list_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
