# Generated by Django 3.2.8 on 2021-12-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20211202_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_list',
            options={'verbose_name_plural': '제품 리스트'},
        ),
        migrations.AddField(
            model_name='product',
            name='displayed_name',
            field=models.CharField(blank=True, editable=False, help_text='자동 지정(입력 X)', max_length=20),
        ),
    ]
