# Generated by Django 3.2.8 on 2021-11-29 06:47

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20211129_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='profile', editable=False, help_text='자동 지정(입력 X)', max_length=20)),
                ('ext', models.CharField(blank=True, editable=False, help_text='자동 지정(입력 X)', max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False)),
                ('video_ok', models.BooleanField(default=False, help_text='동영상 파일을 업로드 할 경우 체크해주세요!!', verbose_name='동영상 여부: ')),
                ('src', models.FileField(blank=True, upload_to=homepage.models.product_profile.auto_naming)),
                ('prefix', models.CharField(default='product_source/profile', max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '혜천문화사 프로필',
            },
        ),
        migrations.CreateModel(
            name='product_rock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='rock', editable=False, help_text='자동 지정(입력 X)', max_length=20)),
                ('ext', models.CharField(blank=True, editable=False, help_text='자동 지정(입력 X)', max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False)),
                ('video_ok', models.BooleanField(default=False, help_text='동영상 파일을 업로드 할 경우 체크해주세요!!', verbose_name='동영상 여부: ')),
                ('src', models.FileField(blank=True, upload_to=homepage.models.product_rock.auto_naming)),
                ('prefix', models.CharField(default='product_source/rock', max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '석부작 작품',
            },
        ),
        migrations.CreateModel(
            name='product_wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='wedding', editable=False, help_text='자동 지정(입력 X)', max_length=20)),
                ('ext', models.CharField(blank=True, editable=False, help_text='자동 지정(입력 X)', max_length=20)),
                ('title', models.CharField(blank=True, help_text='페이지에 들어갈 이미지에 대한 제목 ( 입력 안해도 됨 )', max_length=20, verbose_name='제목')),
                ('desc', models.TextField(blank=True, help_text='페이지에 들어갈 이미지에 대한 자세한 설명 (입력 안해도 됨 )', verbose_name='설명')),
                ('link_ok', models.BooleanField(default=False)),
                ('video_ok', models.BooleanField(default=False, help_text='동영상 파일을 업로드 할 경우 체크해주세요!!', verbose_name='동영상 여부: ')),
                ('src', models.FileField(blank=True, upload_to=homepage.models.product_wedding.auto_naming)),
                ('prefix', models.CharField(default='product_source/wedding', max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '웨딩 사진 출력',
            },
        ),
    ]
