# Generated by Django 3.2.9 on 2021-12-03 01:16

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20211202_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성된 날짜'),
        ),
        migrations.AlterField(
            model_name='product',
            name='displayed_name',
            field=models.CharField(blank=True, editable=False, help_text='자동 지정(입력 X)', max_length=20, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ext',
            field=models.CharField(blank=True, editable=False, help_text='자동 지정(입력 X)', max_length=20, verbose_name='확장자'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, editable=False, help_text='자동 지정(입력 X)', max_length=20, verbose_name='파일 이름'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prefix',
            field=models.CharField(default='product_source/', editable=False, max_length=50, verbose_name='미디어 파일 경로'),
        ),
        migrations.AlterField(
            model_name='product',
            name='src',
            field=models.FileField(blank=True, upload_to=homepage.models.product.auto_naming, verbose_name='미디어 파일(클릭시 보여짐)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='업데이트된 날짜'),
        ),
    ]
